<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FiniquitosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('finiquitos')->delete();
        
        \DB::table('finiquitos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'personas_id' => 4,
                'number' => '000001',
                'fecha_incio' => '2013-04-01',
                'fecha_fin' => '2024-08-31',
                'salario_uno' => 6520.0,
                'salario_dos' => 6520.0,
                'salario_tres' => 6520.0,
                'antiguedad_uno' => NULL,
                'antiguedad_dos' => NULL,
                'antiguedad_tres' => NULL,
                'bono_uno' => NULL,
                'bono_dos' => NULL,
                'bono_tres' => NULL,
                'comisiones_uno' => NULL,
                'comisiones_dos' => NULL,
                'comisiones_tres' => NULL,
                'otros_uno' => NULL,
                'otros_dos' => NULL,
                'otros_tres' => NULL,
                'anios' => 11,
                'meses' => 4,
                'dias' => 0,
                'promedio' => 6520.0,
                'area' => 'VOLUNTARIO',
                'cargo' => NULL,
                'vacations' => '10',
                'vacations_pay' => 2173.33,
                'prima_pay' => NULL,
                'aguinaldo_pay' => NULL,
                'oter_pay' => NULL,
                'deductions_one' => NULL,
                'deductions_two' => NULL,
                'deductions_three' => NULL,
                'observaciones' => NULL,
                'user_id' => 1,
                'status_at' => 'pendientes',
                'created_at' => '2024-08-30 23:19:54',
                'updated_at' => '2024-08-31 14:34:05',
                'deleted_at' => '2024-08-31 14:34:05',
            ),
            1 => 
            array (
                'id' => 2,
                'personas_id' => 4,
                'number' => '000002',
                'fecha_incio' => '2013-04-01',
                'fecha_fin' => '2024-08-31',
                'salario_uno' => 6520.0,
                'salario_dos' => 6520.0,
                'salario_tres' => 6520.0,
                'antiguedad_uno' => 450.0,
                'antiguedad_dos' => 450.0,
                'antiguedad_tres' => 450.0,
                'bono_uno' => 450.0,
                'bono_dos' => 450.0,
                'bono_tres' => 1500.0,
                'comisiones_uno' => 1500.0,
                'comisiones_dos' => 1500.0,
                'comisiones_tres' => 450.0,
                'otros_uno' => NULL,
                'otros_dos' => 652.0,
                'otros_tres' => NULL,
                'anios' => 11,
                'meses' => 4,
                'dias' => 30,
                'promedio' => 6970.0,
                'area' => 'VOLUNTARIO',
                'cargo' => NULL,
                'vacations' => '35',
                'vacations_pay' => 8131.67,
                'prima_pay' => NULL,
                'aguinaldo_pay' => 2323.33,
                'oter_pay' => NULL,
                'deductions_one' => NULL,
                'deductions_two' => NULL,
                'deductions_three' => NULL,
                'observaciones' => NULL,
                'user_id' => 1,
                'status_at' => 'pendientes',
                'created_at' => '2024-08-30 23:21:31',
                'updated_at' => '2024-09-04 15:05:30',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'personas_id' => 1,
                'number' => '000003',
                'fecha_incio' => '2021-04-19',
                'fecha_fin' => '2024-08-31',
                'salario_uno' => 3892.23,
                'salario_dos' => 3892.23,
                'salario_tres' => 3892.23,
                'antiguedad_uno' => NULL,
                'antiguedad_dos' => NULL,
                'antiguedad_tres' => NULL,
                'bono_uno' => NULL,
                'bono_dos' => NULL,
                'bono_tres' => NULL,
                'comisiones_uno' => NULL,
                'comisiones_dos' => NULL,
                'comisiones_tres' => NULL,
                'otros_uno' => NULL,
                'otros_dos' => NULL,
                'otros_tres' => NULL,
                'anios' => 3,
                'meses' => 4,
                'dias' => 12,
                'promedio' => 3892.23,
                'area' => 'VOLUNTARIO',
                'cargo' => NULL,
                'vacations' => '25.5',
                'vacations_pay' => 3308.4,
                'prima_pay' => NULL,
                'aguinaldo_pay' => 1297.41,
                'oter_pay' => NULL,
                'deductions_one' => NULL,
                'deductions_two' => NULL,
                'deductions_three' => NULL,
                'observaciones' => NULL,
                'user_id' => 1,
                'status_at' => 'pendientes',
                'created_at' => '2024-08-30 23:25:22',
                'updated_at' => '2024-09-04 13:25:13',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'personas_id' => 38,
                'number' => '000004',
                'fecha_incio' => '2021-04-24',
                'fecha_fin' => '2024-09-30',
                'salario_uno' => 5200.0,
                'salario_dos' => 5200.0,
                'salario_tres' => 5200.0,
                'antiguedad_uno' => 450.0,
                'antiguedad_dos' => 450.0,
                'antiguedad_tres' => 450.0,
                'bono_uno' => NULL,
                'bono_dos' => NULL,
                'bono_tres' => NULL,
                'comisiones_uno' => NULL,
                'comisiones_dos' => NULL,
                'comisiones_tres' => NULL,
                'otros_uno' => NULL,
                'otros_dos' => NULL,
                'otros_tres' => NULL,
                'anios' => 3,
                'meses' => 5,
                'dias' => 6,
                'promedio' => 5650.0,
                'area' => 'VOLUNTARIO',
                'cargo' => NULL,
                'vacations' => '18',
                'vacations_pay' => 3390.0,
                'prima_pay' => NULL,
                'aguinaldo_pay' => NULL,
                'oter_pay' => NULL,
                'deductions_one' => NULL,
                'deductions_two' => NULL,
                'deductions_three' => NULL,
                'observaciones' => NULL,
                'user_id' => 1,
                'status_at' => 'pendientes',
                'created_at' => '2024-08-31 14:32:20',
                'updated_at' => '2024-08-31 14:32:20',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}