<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-06-13 18:52:51',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-10-03 20:50:46',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 3,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-07-16 13:16:01',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 4,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-07-16 13:16:01',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-10-03 20:50:46',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-07-16 13:15:28',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-07-16 13:15:28',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-07-16 13:15:28',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-07-16 13:15:28',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 1,
                'created_at' => '2024-06-13 18:52:51',
                'updated_at' => '2024-10-04 14:38:53',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Grupos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-group',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 1,
                'created_at' => '2024-06-18 13:31:57',
                'updated_at' => '2024-07-16 13:16:01',
                'route' => 'voyager.grupos.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Personas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 2,
                'created_at' => '2024-06-18 13:59:16',
                'updated_at' => '2024-07-16 13:16:01',
                'route' => 'voyager.personas.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Requerimientos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-harddrive',
                'color' => NULL,
                'parent_id' => 18,
                'order' => 2,
                'created_at' => '2024-06-18 19:18:57',
                'updated_at' => '2024-08-25 01:43:33',
                'route' => 'voyager.requerimientos.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Altas Activos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tv',
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 3,
                'created_at' => '2024-06-18 22:53:27',
                'updated_at' => '2024-08-25 01:43:38',
                'route' => 'voyager.altas-activos.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Catalogos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 5,
                'created_at' => '2024-07-06 15:08:33',
                'updated_at' => '2024-10-04 14:38:53',
                'route' => 'voyager.catalogos.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Personas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2024-07-16 13:15:19',
                'updated_at' => '2024-09-25 15:44:10',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Vacaciones',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-campfire',
                'color' => NULL,
                'parent_id' => 18,
                'order' => 1,
                'created_at' => '2024-08-24 15:52:18',
                'updated_at' => '2024-08-25 01:43:29',
                'route' => 'voyager.vacations.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Solicitudes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-window-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2024-08-25 01:43:09',
                'updated_at' => '2024-09-25 15:44:07',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Finiquitos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-skull',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2024-08-28 22:58:59',
                'updated_at' => '2024-10-04 14:38:59',
                'route' => 'voyager.finiquitos.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Polizas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-certificate',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 6,
                'created_at' => '2024-09-05 15:50:34',
                'updated_at' => '2024-10-04 14:39:00',
                'route' => 'voyager.polizas.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Correos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2024-09-25 15:39:33',
                'updated_at' => '2024-09-25 15:44:10',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Inbox',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 1,
                'created_at' => '2024-09-25 15:40:27',
                'updated_at' => '2024-09-25 21:25:40',
                'route' => 'voyager.mail.index',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 2,
                'title' => 'Inicio',
                'url' => '/',
                'target' => '_self',
                'icon_class' => 'voyager-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2024-10-02 22:16:37',
                'updated_at' => '2024-10-04 13:14:51',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 2,
                'title' => 'Contactanos',
                'url' => '/contact',
                'target' => '_self',
                'icon_class' => 'voyager-paper-plane',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2024-10-02 22:19:53',
                'updated_at' => '2024-10-04 13:14:51',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Marcas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 2,
                'created_at' => '2024-10-03 19:52:50',
                'updated_at' => '2024-10-04 14:38:53',
                'route' => 'voyager.marcas.index',
                'parameters' => NULL,
            ),
            25 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-cup',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 3,
                'created_at' => '2024-10-03 20:42:05',
                'updated_at' => '2024-10-04 14:38:53',
                'route' => 'voyager.types.index',
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Parametros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2024-10-03 20:50:25',
                'updated_at' => '2024-10-03 20:50:43',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Productos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-laptop',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 4,
                'created_at' => '2024-10-03 21:01:31',
                'updated_at' => '2024-10-04 14:38:53',
                'route' => 'voyager.productos.index',
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => 32,
                'menu_id' => 2,
                'title' => 'Motocicletas',
                'url' => '/motorcycle',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2024-10-04 14:44:13',
                'updated_at' => '2024-10-04 14:44:22',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 33,
                'menu_id' => 3,
                'title' => 'prolicy',
                'url' => '/policy',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2024-10-04 14:51:29',
                'updated_at' => '2024-10-04 14:51:29',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Chat',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-chat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2024-10-08 21:28:40',
                'updated_at' => '2024-10-08 21:51:27',
                'route' => 'voyager.whatsapp.index',
                'parameters' => 'null',
            ),
        ));
        
        
    }
}