<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VacationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vacations')->delete();
        
        \DB::table('vacations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'personas_id' => 2,
                'number' => '000001',
                'periodo_inicio' => '2021-04-01',
                'periodo_fin' => '2022-04-01',
                'fecha_incio' => '2024-09-02',
                'fecha_fin' => '2024-09-02',
                'dias' => '1',
                'sucursal' => 'TRINIDAD',
                'area' => 'SISTEMAS',
                'cargo' => 'SUB GERENTE DE SISTEMAS',
                'type_vacations' => 'Programada',
                'type_solicitud' => 'Vacacion',
                'observaciones' => NULL,
                'user_id' => 1,
                'status_at' => 'pendientes',
                'created_at' => '2024-08-31 13:45:00',
                'updated_at' => '2024-08-31 13:46:35',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'personas_id' => 49,
                'number' => '000002',
                'periodo_inicio' => NULL,
                'periodo_fin' => NULL,
                'fecha_incio' => '2024-09-20',
                'fecha_fin' => '2024-09-20',
                'dias' => '1/2 DIA',
                'sucursal' => 'TRINIDAD',
                'area' => 'POLIZAS',
                'cargo' => 'ASISTENTE DE OPERACIONES',
                'type_vacations' => 'Motivo personal',
                'type_solicitud' => 'Vacacion',
                'observaciones' => NULL,
                'user_id' => 9,
                'status_at' => 'pendientes',
                'created_at' => '2024-09-18 14:44:24',
                'updated_at' => '2024-09-18 14:44:24',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'personas_id' => 57,
                'number' => '000003',
                'periodo_inicio' => '2023-03-04',
                'periodo_fin' => '2024-03-04',
                'fecha_incio' => '2024-10-03',
                'fecha_fin' => '2024-10-09',
                'dias' => '4.5',
                'sucursal' => 'TRINIDAD',
                'area' => 'COBRANZAS',
                'cargo' => 'EJECUTIVO DE COBRANZAS',
                'type_vacations' => 'Otros',
                'type_solicitud' => 'Vacacion',
                'observaciones' => 'SE REINCORPORA EL JUEVES 10 DE OCTUBRE 2024',
                'user_id' => 13,
                'status_at' => 'pendientes',
                'created_at' => '2024-10-02 22:30:16',
                'updated_at' => '2024-10-02 22:30:16',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'personas_id' => 60,
                'number' => '000004',
                'periodo_inicio' => '2023-09-01',
                'periodo_fin' => '2024-09-01',
                'fecha_incio' => '2024-10-05',
                'fecha_fin' => '2024-10-05',
                'dias' => '0.5',
                'sucursal' => 'TRINIDAD',
                'area' => 'COBRANZAS',
                'cargo' => 'EJECUTIVO DE COBRANZAS',
                'type_vacations' => 'Motivo personal',
                'type_solicitud' => 'Vacacion',
                'observaciones' => 'SE REINCORPORA EL MARTES 08 DE OCTUBRE 2024',
                'user_id' => 13,
                'status_at' => 'pendientes',
                'created_at' => '2024-10-04 22:20:23',
                'updated_at' => '2024-10-04 22:20:23',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'personas_id' => 61,
                'number' => '000005',
                'periodo_inicio' => NULL,
                'periodo_fin' => NULL,
                'fecha_incio' => '2024-10-05',
                'fecha_fin' => '2024-10-05',
                'dias' => '0.5',
                'sucursal' => 'TRINIDAD',
                'area' => 'MOXOS SERVICE',
                'cargo' => 'MECANICO',
                'type_vacations' => 'Otros',
                'type_solicitud' => 'Vacacion',
                'observaciones' => 'PERMISO A CUENTA VACACION',
                'user_id' => 12,
                'status_at' => 'pendientes',
                'created_at' => '2024-10-04 23:17:27',
                'updated_at' => '2024-10-04 23:17:27',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'personas_id' => 62,
                'number' => '000006',
                'periodo_inicio' => NULL,
                'periodo_fin' => NULL,
                'fecha_incio' => '2024-10-08',
                'fecha_fin' => '2024-10-12',
                'dias' => '4.5',
                'sucursal' => 'TRINIDAD',
                'area' => 'MOXOS SERVICE',
                'cargo' => 'MECANICO',
                'type_vacations' => 'Programada',
                'type_solicitud' => 'Vacacion',
                'observaciones' => 'VACACION APROBADA',
                'user_id' => 12,
                'status_at' => 'pendientes',
                'created_at' => '2024-10-05 17:08:10',
                'updated_at' => '2024-10-05 17:08:10',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'personas_id' => 64,
                'number' => '000007',
                'periodo_inicio' => '2023-02-01',
                'periodo_fin' => '2024-02-01',
                'fecha_incio' => '2024-10-11',
                'fecha_fin' => '2024-10-19',
                'dias' => '7',
                'sucursal' => 'TRINIDAD',
                'area' => 'COBRANZAS',
                'cargo' => 'EJECUTIVO DE COBRANZAS',
                'type_vacations' => 'Otros',
                'type_solicitud' => 'Vacacion',
                'observaciones' => 'SE REINCORPORA EL LUNES 21 DE OCTUBRE 2024',
                'user_id' => 13,
                'status_at' => 'pendientes',
                'created_at' => '2024-10-09 12:22:00',
                'updated_at' => '2024-10-09 12:23:05',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'personas_id' => 65,
                'number' => '000008',
                'periodo_inicio' => '2023-02-01',
                'periodo_fin' => '2024-02-01',
                'fecha_incio' => '2024-10-15',
                'fecha_fin' => '2024-10-15',
                'dias' => '0.5',
                'sucursal' => 'TRINIDAD',
                'area' => 'COBRANZAS',
                'cargo' => 'EJECUTIVO DE COBRANZAS',
                'type_vacations' => 'Motivo personal',
                'type_solicitud' => 'Cumpleaños',
                'observaciones' => 'SE REINCORPORA EL MIÉRCOLES 16 DE OCTUBRE 2024',
                'user_id' => 13,
                'status_at' => 'pendientes',
                'created_at' => '2024-10-09 13:20:00',
                'updated_at' => '2024-10-15 12:47:46',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'personas_id' => 68,
                'number' => '000009',
                'periodo_inicio' => NULL,
                'periodo_fin' => NULL,
                'fecha_incio' => '2024-10-14',
                'fecha_fin' => '2024-10-19',
                'dias' => '5.5',
                'sucursal' => 'TRINIDAD',
                'area' => 'MOXOS SERVICE',
                'cargo' => 'MECANICO',
                'type_vacations' => 'Programada',
                'type_solicitud' => 'Vacacion',
                'observaciones' => NULL,
                'user_id' => 12,
                'status_at' => 'pendientes',
                'created_at' => '2024-10-12 17:03:54',
                'updated_at' => '2024-10-12 17:03:54',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'personas_id' => 1,
                'number' => '000010',
                'periodo_inicio' => NULL,
                'periodo_fin' => NULL,
                'fecha_incio' => '2024-10-15',
                'fecha_fin' => '2024-10-21',
                'dias' => '5 1/2',
                'sucursal' => 'Trinidad',
                'area' => 'Ssitemas',
                'cargo' => 'Asistente de Sitemas',
                'type_vacations' => 'Programada',
                'type_solicitud' => 'Vacacion',
                'observaciones' => 'Volviendo a mis funciones laborales el día martes 22 de octubre de 2024',
                'user_id' => 1,
                'status_at' => 'pendientes',
                'created_at' => '2024-10-14 14:07:00',
                'updated_at' => '2024-10-14 14:13:13',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}